spring:
  application:
    name: Gateway Limiter
  redis:
    database: 1
    host: 192.168.20.10
  cloud:
    consul:
      discovery:
        register: false
      host: 192.168.20.10
      port: 8500
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: test-ip
          uri: lb://service-provider
          predicates:
            - Path=/hello/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 1
                  burstCapacity: 2
                key-resolver: "#{@ipKeyResolver}"

server:
  port: 8221

management:
  endpoints:
    web:
      exposure:
        include: gateway

#feign:
#  sentinel:
#    enabled: false