package security;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.UUID;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;

@Slf4j
class MyTest {

  @Test
  void test1() {
    String rawId = UUID.nameUUIDFromBytes("Some text".getBytes()).toString();
    log.info("rawId generated by hard coding: {}", rawId);

    SecureRandom randomGenerator = new SecureRandom();
    int randomNumber = randomGenerator.nextInt();
    String randomDigits = Integer.toString(randomNumber);
    try {
      MessageDigest encryptor = MessageDigest.getInstance("SHA-1");
      byte[] rawIdBytes2 = encryptor.digest(randomDigits.getBytes());
      String rawId2 = UUID.nameUUIDFromBytes(rawIdBytes2).toString();
      log.info("rawId generated by random number: {}", rawId2);
    } catch (NoSuchAlgorithmException e) {
      throw new RuntimeException(e);
    }
  }
}
