spring:
  application:
    name: service-provider
  cloud:
    provider:
      name: p1
    consul:
      discovery:
        heartbeat:
          enabled: true
      host: 192.168.20.10
      port: 8500

server:
  port: 8220