spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: hello Route
          uri: http://www.phei.com.cn
          predicates:
            - Path=/hello
        - id: Fault-Tolerance Routing
          uri: forward:/notfound
          predicates:
            - Path=/**

server:
  port: 8220