spring:
  application:
    name: spring-security-demo
  security:
    oauth2:
      client:
        registration:
          message-client-auth-code:
        provider:
          keycloak:
            

server:
  port: 8080